let words = {
    'begin': [
        {word: "apple",hint: "A red or green fruit"},
        {word: "banana",hint: "A long, curved yellow fruit"},
        {word: "bread",hint: "Food made from flour"},
        {word: "milk",hint: "A white liquid from cows"},
        {word: "table",hint: "A piece of furniture with a flat top"},
        {word: "chair",hint: "Something you sit on"},
        {word: "bed",hint: "A place where you sleep"},
        {word: "father",hint: "A male parent"},
        {word: "mother",hint: "A female parent"},
        {word: "run",hint: "Moving fast on foot"},
        {word: "eat",hint: "What you do with food"},
        {word: "drink",hint: "To take liquid into the mouth"},
        {word: "sleep",hint: "To rest with your eyes closed"},
        {word: "play",hint: "What children love to do"},
        {word: "book",hint: "Something you read"},
        {word: "pen",hint: "A tool for writing"},
        {word: "teacher",hint: "A person who teaches students"},
        {word: "pocket",hint: "A bag for carrying small items"},
        {word: "classroom",hint: "A place where students learn"},
        {word: "expert",hint: "Person with extensive knowledge"},
        
    ],
    'intermediate': [
        {word: "engineer",hint: "A person who builds machines"},
        {word: "lawyer",hint: "A person who gives legal advice"},
        {word: "passport",hint: "An official document for travel"},
        {word: "luggage",hint: "Bags used for traveling"},
        {word: "nervous",hint: "Feeling worried or afraid"},
        {word: "excited",hint: "Feeling happy about something fun"},
        {word: "discussion",hint: "Talking about a topic with others"},
        {word: "opinion",hint: "What you think about something"},
        {word: "hypothesis",hint: "An idea that needs to be tested"},
        {word: "architect",hint: "A person who designs building"},
        {word: "negotiation",hint: "Discussing something to reach an agreement"},
        {word: "investment",hint: "Putting money into something for profit"},
        {word: "revenue",hint: "Income generated from business or work"},
        {word: "inflation",hint: "The rise in the price of goods over time"},
        {word: "frustration",hint: "Feeling annoyed and upset"},
        {word: "embarrassed",hint: "Feeling shy or ashamed"},
        {word: "robotics",hint: "The study of robots"},
        {word: "fiscal",hint: "Related to government finances"},
        {word: "subsidy",hint: "financial support from the government"},
        {word: "appeal",hint: "To make a request for help" },
    ],
    'advanced': [
        {word: "perception", hint: "Ability to become aware of something" },
        {word: "algorithm", hint: "A step-by-step procedure for calculations" },
        {word: "paradox", hint: "A seemingly self-contradictory statement" },
        {word: "sophisticated", hint: "Complex and advanced" },
        {word: "manipulate", hint: "To handle or control in a skillful manner" },
        {word: "innovation", hint: "The introduction of something new" },
        {word: "sustainable", hint: "Capable of being maintained over time" },
        {word: "entrepreneur", hint: "A person who starts a business" },
        {word: "collaboration", hint: "Working together to achieve a goal" },
        {word: "synchronize", hint: "To occur at the same time" },
        {word: "optimization", hint: "The act of making something as effective as possible" },
        {word: "infrastructure", hint: "The basic physical and organizational structures" },
        {word: "transformation", hint: "A marked change in form, nature, or appearance" },
        {word: "wholehearted", hint: "With complete sincerity and commitment" },
        {word: "interconnected", hint: "Linked together" },
        {word: "resilience", hint: "The ability to recover from difficulties"},
        {word: "kinesthetic", hint: "Relating to bodily movement" },
        {word: "multicultural", hint: "Relating to or containing several cultural"},
        {word: "comprehensive", hint: "Including all or nearly all elements or aspects of something" },
        {word: "nonetheless", hint: "In spite of that; nevertheless" },

         
    ]
};
