let words = {
    'begin': [
        {word: "&lt;!DOCTYPE&gt;",hint: "กำหนดประเภทของเอกสาร HTML"},
        {word: "&lt;html&gt;",hint: "แท็กหลักที่ครอบเนื้อหาทั้งหมดของเว็บ"},
        {word: "&lt;head&gt;",hint: "ส่วนหัวของเอกสาร ใช้เก็บ metadata"},
        {word: "&lt;title&gt;",hint: "ชื่อของหน้าเว็บที่แสดงในแท็บของเบราว์เซอร์"},
        {word: "&lt;meta&gt;",hint: "กำหนดข้อมูลเมตา"},
        {word: "&lt;link&gt;",hint: "ใช้เชื่อมโยงไฟล์ภายนอก"},
        {word: "&lt;style&gt;",hint: "ใช้เขียน CSS ภายใน HTML"},
        {word: "&lt;script&gt;",hint: "ใช้เพิ่ม JavaScript ลงใน HTML"},
        {word: "&lt;body&gt;",hint: "ส่วนที่ใช้แสดงเนื้อหาบนเว็บ"},
        {word: "&lt;h1&gt;-&lt;h6&gt;",hint: "แท็กสำหรับหัวข้อ (ใหญ่สุด-เล็กสุด)"},
        {word: "&lt;p&gt;",hint: "ย่อหน้าข้อความ"},
        {word: "&lt;br&gt;",hint: "ขึ้นบรรทัดใหม่ (ไม่ต้องปิดแท็ก)"},
        {word: "&lt;hr&gt;",hint: "เส้นคั่นแนวนอน"},
        {word: "&lt;b&gt;",hint: "ทำตัวหนา (ไม่เน้นความสำคัญ)"},
        {word: "&lt;strong&gt;",hint: "ทำตัวหนา (มีความสำคัญ)"},
        {word: "&lt;i&gt;",hint: "ทำตัวเอียง (ไม่เน้นความสำคัญ)"},
        {word: "&lt;em&gt;",hint: "ทำตัวเอียง (เน้นความสำคัญ)"},
        {word: "&lt;mark&gt;",hint: "ไฮไลต์ข้อความ"},
        {word: "&lt;small&gt;",hint: "ข้อความขนาดเล็ก"},
        {word: "&lt;del&gt;",hint: "ขีดฆ่าข้อความ"},
        {word: "&lt;ins&gt;",hint: "ขีดเส้นใต้ข้อความ"},
        {word: "&lt;sub&gt;",hint: "ตัวห้อย (เช่น H₂O)"},
        {word: "&lt;sup&gt;",hint: "ตัวยก (เช่น X²)"},
        {word: "&lt;blockquote&gt;",hint: "ใช้อ้างอิงข้อความจากแหล่งอื่น"},
        {word: "&lt;cite&gt;",hint: "ใช้อ้างอิงชื่อเรื่องของงาน"},
        {word: "&lt;a&gt;",hint: "ใช้สร้างลิงก์ไปยังหน้าอื่น"},
        {word: "&lt;nav&gt;",hint: "ใช้สำหรับเมนูนำทาง"},
        {word: "&lt;ul&gt;",hint: "รายการแบบไม่มีลำดับ (แสดงเป็น bullet points)"},
        {word: "&lt;ol&gt;",hint: "รายการแบบมีลำดับ (แสดงเป็นตัวเลข)"},
        {word: "&lt;li&gt;",hint: "รายการใน &lt;ul&gt; หรือ &lt;ol&gt;"},
        {word: "&lt;dl&gt;",hint: "รายการคำอธิบาย"},
        {word: "&lt;dt&gt;",hint: "หัวข้อใน &lt;dl&gt;"},
        {word: "&lt;dd&gt;",hint: "คำอธิบายของ &lt;dt&gt;"},
        {word: "&lt;table&gt;",hint: "ใช้สร้างตาราง"},
        {word: "&lt;tr&gt;",hint: "แถวของตาราง"},
        {word: "&lt;th&gt;",hint: "หัวข้อของคอลัมน์ (ตัวหนาและอยู่ตรงกลาง)"},
        {word: "&lt;td&gt;",hint: "เซลล์ของข้อมูล"},
        {word: "&lt;form&gt;",hint: "ฟอร์มสำหรับรับข้อมูลจากผู้ใช้"},
        {word: "&lt;input&gt;",hint: "ช่องกรอกข้อมูล (text, password, email ฯลฯ)"},
        {word: "&lt;button&gt;",hint: "ปุ่มกด"},
    ],
    
};