let words = {
    'begin': [
        {word: "Apple",hint: "แอปเปิ้ล"},
        {word: "Banana",hint: "กล้วย"},
        {word: "Bread",hint: "ขนมปัง"},
        {word: "Milk",hint: "นม"},
        {word: "Table",hint: "โต๊ะ"},
        {word: "Chair",hint: "เก้าอี้"},
        {word: "Bed",hint: "เตียง"},
        {word: "Father",hint: "พ่อ"},
        {word: "Mother",hint: "แม่"},
        {word: "Run",hint: "วิ่ง"},
        {word: "Eat",hint: "กิน"},
        {word: "Drink",hint: "ดื่ม"},
        {word: "Sleep",hint: "นอน"},
        {word: "Play",hint: "เล่น"},
        {word: "Book",hint: "หนังสือ"},
        {word: "Pen",hint: "ปากกา"},
        {word: "Teacher",hint: "ครู"},
        {word: "Pocket",hint: "กระเป๋า"},
        {word: "Classroom",hint: "ห้องเรียน"},
        {word: "Expert",hint: "ผู้เชี่ยวชาญ"},
        {word: "Apple",hint: "แอปเปิ้ล"},
        {word: "Banana",hint: "กล้วย"},
        {word: "Bread",hint: "ขนมปัง"},
        {word: "Milk",hint: "นม"},
        {word: "Table",hint: "โต๊ะ"},
        {word: "Chair",hint: "เก้าอี้"},
        {word: "Bed",hint: "เตียง"},
        {word: "Father",hint: "พ่อ"},
        {word: "Mother",hint: "แม่"},
        {word: "Run",hint: "วิ่ง"},
        {word: "Eat",hint: "กิน"},
        {word: "Drink",hint: "ดื่ม"},
        {word: "Sleep",hint: "นอน"},
        {word: "Play",hint: "เล่น"},
        {word: "Book",hint: "หนังสือ"},
        {word: "Pen",hint: "ปากกา"},
        {word: "Teacher",hint: "ครู"},
        {word: "Pocket",hint: "กระเป๋า"},
        {word: "Classroom",hint: "ห้องเรียน"},
        {word: "Expert",hint: "ผู้เชี่ยวชาญ"},
    ],
    'advanced': [
        {word: "perception", hint: "Ability to become aware of something" },
        {word: "algorithm", hint: "A step-by-step procedure for calculations" },
        {word: "paradox", hint: "A seemingly self-contradictory statement" },
        {word: "sophisticated", hint: "Complex and advanced" },
        {word: "manipulate", hint: "To handle or control in a skillful manner" },
        {word: "innovation", hint: "The introduction of something new" },
        {word: "sustainable", hint: "Capable of being maintained over time" },
        {word: "entrepreneur", hint: "A person who starts a business" },
        {word: "collaboration", hint: "Working together to achieve a goal" },
        {word: "synchronize", hint: "To occur at the same time" },
        {word: "optimization", hint: "The act of making something as effective as possible" },
        {word: "infrastructure", hint: "The basic physical and organizational structures" },
        {word: "transformation", hint: "A marked change in form, nature, or appearance" },
        {word: "wholehearted", hint: "With complete sincerity and commitment" },
        {word: "interconnected", hint: "Linked together" },
        {word: "resilience", hint: "The ability to recover from difficulties"},
        {word: "kinesthetic", hint: "Relating to bodily movement" },
        {word: "multicultural", hint: "Relating to or containing several cultural"},
        {word: "comprehensive", hint: "Including all or nearly all elements or aspects of something" },
        {word: "nonetheless", hint: "In spite of that; nevertheless" },
        {word: "perception", hint: "Ability to become aware of something" },
        {word: "algorithm", hint: "A step-by-step procedure for calculations" },
        {word: "paradox", hint: "A seemingly self-contradictory statement" },
        {word: "sophisticated", hint: "Complex and advanced" },
        {word: "manipulate", hint: "To handle or control in a skillful manner" },
        {word: "innovation", hint: "The introduction of something new" },
        {word: "sustainable", hint: "Capable of being maintained over time" },
        {word: "entrepreneur", hint: "A person who starts a business" },
        {word: "collaboration", hint: "Working together to achieve a goal" },
        {word: "synchronize", hint: "To occur at the same time" },
        {word: "optimization", hint: "The act of making something as effective as possible" },
        {word: "infrastructure", hint: "The basic physical and organizational structures" },
        {word: "transformation", hint: "A marked change in form, nature, or appearance" },
        {word: "wholehearted", hint: "With complete sincerity and commitment" },
        {word: "interconnected", hint: "Linked together" },
        {word: "resilience", hint: "The ability to recover from difficulties"},
        {word: "kinesthetic", hint: "Relating to bodily movement" },
        {word: "multicultural", hint: "Relating to or containing several cultural"},
        {word: "comprehensive", hint: "Including all or nearly all elements or aspects of something" },
        {word: "nonetheless", hint: "In spite of that; nevertheless" },
    ]
};