let words = {
    'advanced': [
        {word: "&lt;thead&gt;",hint: "กลุ่มส่วนหัวของตาราง"},
        {word: "&lt;tbody&gt;",hint: "กลุ่มเนื้อหาหลักของตาราง"},
        {word: "&lt;tfoot&gt;",hint: "กลุ่มส่วนท้ายของตาราง"},
        {word: "&lt;col&gt;",hint: "กำหนดคุณสมบัติของคอลัมน์"},
        {word: "&lt;colgroup&gt;",hint: "จัดกลุ่มคอลัมน์ในตาราง"},
        {word: "&lt;textarea&gt;",hint: "ช่องกรอกข้อความหลายบรรทัด"},
        {word: "&lt;select&gt;",hint: "เมนูเลือกค่า"},
        {word: "&lt;option&gt;",hint: "ตัวเลือกใน &lt;select&gt;"},
        {word: "&lt;optgroup&gt;",hint: "กลุ่มตัวเลือกใน &lt;select&gt;"},
        {word: "&lt;label&gt;",hint: "ป้ายกำกับ &lt;input&gt;"},
        {word: "&lt;fieldset&gt;",hint: "กลุ่มของฟอร์ม"},
        {word: "&lt;legend&gt;",hint: "หัวข้อของ &lt;fieldset&gt;"},
        {word: "&lt;datalist&gt;",hint: "รายการค่าที่แนะนำ"},
        {word: "&lt;output&gt;",hint: "แสดงค่าผลลัพธ์"},
        {word: "&lt;progress&gt;",hint: "แสดงความคืบหน้า"},
        {word: "&lt;meter&gt;",hint: "วัดระดับค่า"},
        {word: "&lt;dialog&gt;",hint: "กล่องโต้ตอบ"},
        {word: "&lt;menu&gt;",hint: "เมนูคำสั่ง"},
        {word: "&lt;template&gt;",hint: "เทมเพลต HTML ซ่อนอยู่"},
        {word: "&lt;slot&gt;",hint: "ช่องสำหรับ Web Components"},
        {word: "&lt;img&gt;",hint: "แสดงรูปภาพ"},
        {word: "&lt;audio&gt;",hint: "ใส่ไฟล์เสียง"},
        {word: "&lt;video&gt;",hint: "ใส่ไฟล์วิดีโอ"},
        {word: "&lt;iframe&gt;",hint: "ฝังหน้าเว็บ"},
        {word: "&lt;embed&gt;",hint: "ฝังเนื้อหาเก่า"},
        {word: "&lt;object&gt;",hint: "ฝังเนื้อหาภายนอก"},
        {word: "&lt;param&gt;",hint: "พารามิเตอร์ &lt;object&gt;"},
        {word: "&lt;picture&gt;",hint: "ใช้แสดงรูปภาพแบบ responsive"},
        {word: "&lt;source&gt;",hint: "แหล่งข้อมูล &lt;audio> / &lt;video&gt;"},
        {word: "&lt;track&gt;",hint: "คำบรรยายวิดีโอ"},
        {word: "&lt;base&gt;",hint: "URL พื้นฐาน"},
        {word: "&lt;noscript&gt;",hint: "แสดงเนื้อหาเมื่อ JS ปิด"},
        {word: "&lt;header&gt;",hint: "ส่วนหัว"},
        {word: "&lt;footer&gt;",hint: "ส่วนท้าย"},
        {word: "&lt;section&gt;",hint: "กลุ่มเนื้อหา"},
        {word: "&lt;article&gt;",hint: "บทความ"},
        {word: "&lt;aside&gt;",hint: "เนื้อหาข้างเคียง"},
        {word: "&lt;main&gt;",hint: "เนื้อหาหลัก"},
        {word: "&lt;figure&gt;",hint: "กลุ่มของรูปภา"},
        {word: "&lt;figcaption&gt;",hint: "คำบรรยายใต้รูป"},
    ],

};