let words = {
    'advanced': [
        {word: "<thead>",hint: "กลุ่มส่วนหัวของตาราง"},
        {word: "<tbody>",hint: "กลุ่มเนื้อหาหลักของตาราง"},
        {word: "<tfoot>",hint: "กลุ่มส่วนท้ายของตาราง"},
        {word: "<col>",hint: "กำหนดคุณสมบัติของคอลัมน์"},
        {word: "<colgroup>",hint: "จัดกลุ่มคอลัมน์ในตาราง"},
        {word: "<textarea>",hint: "ช่องกรอกข้อความหลายบรรทัด"},
        {word: "<select>",hint: "เมนูเลือกค่า"},
        {word: "<option>",hint: "ตัวเลือกใน <select>"},
        {word: "<optgroup>",hint: "กลุ่มตัวเลือกใน <select>"},
        {word: "<label>",hint: "ป้ายกำกับ <input>"},
        {word: "<fieldset>",hint: "กลุ่มของฟอร์ม"},
        {word: "<legend>",hint: "หัวข้อของ <fieldset>"},
        {word: "<datalist>",hint: "รายการค่าที่แนะนำ"},
        {word: "<output>",hint: "แสดงค่าผลลัพธ์"},
        {word: "<progress>",hint: "แสดงความคืบหน้า"},
        {word: "<meter>",hint: "วัดระดับค่า"},
        {word: "<dialog>",hint: "กล่องโต้ตอบ"},
        {word: "<menu>",hint: "เมนูคำสั่ง"},
        {word: "<template>",hint: "เทมเพลต HTML ซ่อนอยู่"},
        {word: "<slot>",hint: "ช่องสำหรับ Web Components"},
        {word: "<img>",hint: "แสดงรูปภาพ"},
        {word: "<audio>",hint: "ใส่ไฟล์เสียง"},
        {word: "<video>",hint: "ใส่ไฟล์วิดีโอ"},
        {word: "<iframe>",hint: "ฝังหน้าเว็บ"},
        {word: "<embed>",hint: "ฝังเนื้อหาเก่า"},
        {word: "<object>",hint: "ฝังเนื้อหาภายนอก"},
        {word: "<param>",hint: "พารามิเตอร์ <object>"},
        {word: "<picture>",hint: "ใช้แสดงรูปภาพแบบ responsive"},
        {word: "<source>",hint: "แหล่งข้อมูล <audio> / <video>"},
        {word: "<track>",hint: "คำบรรยายวิดีโอ"},
        {word: "<base>",hint: "URL พื้นฐาน"},
        {word: "<noscript>",hint: "แสดงเนื้อหาเมื่อ JS ปิด"},
        {word: "<header>",hint: "ส่วนหัว"},
        {word: "<footer>",hint: "ส่วนท้าย"},
        {word: "<section>",hint: "กลุ่มเนื้อหา"},
        {word: "<article>",hint: "บทความ"},
        {word: "<aside>",hint: "เนื้อหาข้างเคียง"},
        {word: "<main>",hint: "เนื้อหาหลัก"},
        {word: "<figure>",hint: "กลุ่มของรูปภา"},
        {word: "<figcaption>",hint: "คำบรรยายใต้รูป"},
    ],

};