let words = {
    'begin': [
        {word: "Apple",hint: "แอปเปิ้ล"},
        {word: "Banana",hint: "กล้วย"},
        {word: "Bread",hint: "ขนมปัง"},
        {word: "Milk",hint: "นม"},
        {word: "Table",hint: "โต๊ะ"},
        {word: "Chair",hint: "เก้าอี้"},
        {word: "Bed",hint: "เตียง"},
        {word: "Father",hint: "พ่อ"},
        {word: "Mother",hint: "แม่"},
        {word: "Run",hint: "วิ่ง"},
        {word: "Eat",hint: "กิน"},
        {word: "Drink",hint: "ดื่ม"},
        {word: "Sleep",hint: "นอน"},
        {word: "Play",hint: "เล่น"},
        {word: "Book",hint: "หนังสือ"},
        {word: "Pen",hint: "ปากกา"},
        {word: "Teacher",hint: "ครู"},
        {word: "Pocket",hint: "กระเป๋า"},
        {word: "Classroom",hint: "ห้องเรียน"},
        {word: "Expert",hint: "ผู้เชี่ยวชาญ"},
        
    ],
    'intermediate': [
        {word: "Engineer",hint: "วิศวกร"},
        {word: "Lawyer",hint: "ทนาย"},
        {word: "Passport",hint: "หนังสือเดินทาง"},
        {word: "Luggage",hint: "กระเป๋าเดินทาง"},
        {word: "Nervous",hint: "รู้สึกกังวล"},
        {word: "Excited",hint: "รู้สึกตื่นเต้น"},
        {word: "Discussion",hint: "การสนทนา"},
        {word: "Opinion",hint: "ความคิดเห็น"},
        {word: "Hypothesis",hint: "สมมติฐาน"},
        {word: "Architect",hint: "สถาปนิก"},
        {word: "Negotiation",hint: "การเจรจาต่อรอง"},
        {word: "Investment",hint: "การลงทุน"},
        {word: "Revenue",hint: "รายได้"},
        {word: "Inflation",hint: "เงินเฟ้อ"},
        {word: "Frustration",hint: "ความผิดหวัง"},
        {word: "Embarrassed",hint: "รู้สึกอับอาย"},
        {word: "Robotics",hint: "การทำหุ่นยนต์"},
        {word: "Fiscal",hint: "เกี่ยวกับการเงิน"},
        {word: "Subsidy",hint: "เงินช่วยเหลือ"},
        {word: "Appeal",hint: "อุทธรณ์" },
    ],
    'advanced': [
        {word: "Perception", hint: "การรับรู้" },
        {word: "Algorithm", hint: "ขั้นตอนวิธี" },
        {word: "Paradox", hint: "ความขัดแย้ง" },
        {word: "Sophisticated", hint: "ช่ำชอง" },
        {word: "Manipulate", hint: "จัดการ" },
        {word: "Innovation", hint: "นวัตกรรม" },
        {word: "Sustainable", hint: "ยั่งยืน" },
        {word: "Entrepreneur", hint: "ผู้ประกอบการ" },
        {word: "Collaboration", hint: "การทำงานร่วมกัน" },
        {word: "Synchronize", hint: "ทำให้เกิดขึ้นในเวลาเดียวกัน" },
        {word: "Optimization", hint: "การเพิ่มประสิทธิภาพ" },
        {word: "Infrastructure", hint: "โครงสร้างพื้นฐาน" },
        {word: "Transformation", hint: "การเปลี่ยนแปลง" },
        {word: "Wholehearted", hint: "เต็มใจ" },
        {word: "Interconnected", hint: "เชื่อมโยงกัน" },
        {word: "Resilience", hint: "ความยืดหยุ่น"},
        {word: "Kinesthetic", hint: "การรับรู้ทางกาย" },
        {word: "Multicultural", hint: "พหุวัฒนธรรม"},
        {word: "Comprehensive", hint: "ครอบคลุม" },
        {word: "Nonetheless", hint: "กระนั้นก็ตาม" },

         
    ]
};
